### ISSUE TITLE
Do not crash the server if external backend not available

### ISSUE THREAD

**Issue by mathieucarbou** [mathieucarbou/megatron#13]

**Comment by mathieucarbou** [comment]
```
 - megatron.prometheus.statsd.async=true
 - megatron.prometheus.statsd.enable=true
 - megatron.prometheus.statsd.port=9125
 - megatron.prometheus.statsd.prefix=megatron
 - megatron.prometheus.statsd.queueSize=-1
 - megatron.prometheus.statsd.server=statsd-exporter
 - megatron.prometheus.statsd.tags=[stripe:stripe1, cluster:MyCluster]
java.io.UncheckedIOException: java.net.UnknownHostException: statsd-exporter: Name does not resolve
        at com.mycila.megatron.udp.NonBlockingUdpClient.resolve(NonBlockingUdpClient.java:128)
        at com.mycila.megatron.udp.NonBlockingUdpClient.<init>(NonBlockingUdpClient.java:51)
        at com.mycila.megatron.AbstractMegatronUdpPlugin.enable(AbstractMegatronUdpPlugin.java:40)
        at com.mycila.megatron.plugins.prometheus.statsd.MegatronPrometheusStatsDPlugin.enable(MegatronPrometheusStatsDPlugin.java:40)
        at com.mycila.megatron.AbstractMegatronPlugin.init(AbstractMegatronPlugin.java:123)
        at com.mycila.megatron.DisoveringMegatronPlugins.lambda$init$3(DisoveringMegatronPlugins.java:73)
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
        at com.mycila.megatron.DisoveringMegatronPlugins.init(DisoveringMegatronPlugins.java:73)
        at com.mycila.megatron.server.service.MegatronServiceProvider.initialize(MegatronServiceProvider.java:88)
        at com.tc.services.TerracottaServiceProviderRegistryImpl.loadClasspathBuiltins(TerracottaServiceProviderRegistryImpl.java:91)
        at com.tc.services.TerracottaServiceProviderRegistryImpl.initialize(TerracottaServiceProviderRegistryImpl.java:77)
        at com.tc.objectserver.impl.DistributedObjectServer.start(DistributedObjectServer.java:439)
        at com.tc.server.TCServerImpl.startDSOServer(TCServerImpl.java:384)
        at com.tc.server.TCServerImpl.access$300(TCServerImpl.java:73)
        at com.tc.server.TCServerImpl$StartAction.execute(TCServerImpl.java:361)
        at com.tc.lang.StartupHelper.startUp(StartupHelper.java:52)
        at com.tc.server.TCServerImpl.startServer(TCServerImpl.java:378)
        at com.tc.server.TCServerImpl.start(TCServerImpl.java:199)
        at com.tc.server.TCServerMain.main(TCServerMain.java:74)
Caused by: java.net.UnknownHostException: statsd-exporter: Name does not resolve
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at java.net.InetAddress.getByName(InetAddress.java:1076)
        at com.mycila.megatron.udp.NonBlockingUdpClient.resolve(NonBlockingUdpClient.java:126)
        ... 18 more
```
